getguesstimate/guesstimate-app

- package.json
- src/css/main.styl
- src/layouts/application.js
- src/models/repo-collection.js
- src/models/repo.js
- src/router.js
- src/views/repos/new.js
- src/views/repos/show.js
- webpack.config.js
1.Added Repo List dropdown button.
2.Added Cancel button to "new repo" page.
3.Added a description field to be saved along with the repo.
To do: Links on the dropdown on the repo page dont work. This needs to be fixed
> Ui additions and fixes

- src/components/lib/histogram.js
> Histogram fix

- src/routes/layouts/login/index.js
Addresses https://github.com/getguesstimate/guesstimate-app/issues/66
> Wait for user id to show my models

- src/components/pages/faq/index.js
- src/components/pages/faq/style.css
- src/routes/layouts/login/index.js
- src/routes/router.js
https://github.com/getguesstimate/guesstimate-app/issues/71
Lots of people were asking the same questions, seemed high priority.
> Add an Faq

- package.json
- src/components/distributions/editor/data-viewer/index.js
- src/components/distributions/editor/data-viewer/style.css
- src/components/distributions/editor/guesstimate-type-icon.js
- src/components/distributions/editor/index.js
- src/components/distributions/editor/style.css
- src/components/distributions/editor/text-input.js
- src/components/metrics/card/index.js
- src/components/metrics/modal/index.js
- src/components/metrics/modal/style.css
- src/components/simulations/histogram/index.js
- src/lib/engine/guesstimate.js
- src/lib/guesstimator/formatter/formatters/Data.js
- src/lib/guesstimator/formatter/formatters/DistributionPointText.js
- src/lib/guesstimator/formatter/index-test.js
- src/lib/guesstimator/formatter/index.js
- src/lib/guesstimator/index-test.js
- src/lib/guesstimator/samplers/Data.js
- src/lib/guesstimator/types.js
- src/modules/guesstimate_form/actions.js
- src/modules/guesstimate_form/reducer.js
- src/modules/guesstimates/actions.js
- src/styles/variables.css
This PR enables custom data in cells instead of the existing distributions.  This data is resampled (in order to handle any amount of custom data), then used directly in calculations.  
Right now this is particularly handy with [Distshaper](http://smpro.ca/pjs/distshaper/), a tool for making custom distributions.  It's possible to create distributions from Distshaper, then copy & paste the exact values into the value of field of a guesstimate.  Video below.
> Custom Data Input

- src/components/lib/iubenda_privacy_policy.js
- src/components/pages/privacy_policy/index.js
- src/components/utility/links/index.js
- src/routes/home/index.js
- src/routes/layouts/application/index.js
- src/routes/layouts/application/style.css
- src/routes/layouts/footer/index.js
- src/routes/layouts/footer/style.css
- src/routes/layouts/login/index.js
- src/routes/main.css
- src/routes/router.js
- src/styles/variables.css
> Add footer to bottom with Terms and Privacy Policy

- package.json
- src/components/spaces/new/index.js
- src/components/spaces/new/privacy-toggle/index.js
- src/components/spaces/new/privacy-toggle/style.css
- src/components/spaces/new/style.css
- src/lib/engine/me/index.js
- src/modules/me/actions.js
- src/modules/users/actions.js
This is for the following story: https://github.com/getguesstimate/guesstimate-app/issues/80
> Model privacy option button

- src/components/lib/grid/grid.css
- src/components/metrics/card/name/style.css
- src/components/metrics/card/style.css
- src/components/metrics/card/token/style.css
- src/components/spaces/show/canvasViewForm.js
- src/components/spaces/show/sidebar.js
- src/components/spaces/show/style.css
- src/components/utility/card/style.css
- src/components/utility/tooltip/style.css
- src/lib/guesstimator/samplers/None.js
- src/modules/canvas_state/prop_type.js
- src/styles/variables.css
> Modified math canvas UI to moderate bold colors, closes #140

- src/components/distributions/editor/index.js
- src/components/metrics/card/index.js
- src/components/metrics/modal/index.js
> Metric Modal editing does not work - closes #128

- src/routes/home/index.js
Submitting on behalf of Jacob, as Jacob was offended at the non curly quote.
> Fixing curly brace.

- README.md
- package.json
- src/components/layouts/main/style.css
- src/components/pages/faq/index.js
- src/components/spaces/list_item/index.js
- src/components/spaces/new/index.js
- src/components/spaces/show/header.js
- src/components/spaces/show/index.js
- src/components/spaces/show/style.css
- src/components/subscriptions/FirstSubscription/FirstSubscription.js
- src/components/subscriptions/FirstSubscription/NewOrder.js
- src/components/subscriptions/FirstSubscription/style.css
- src/components/subscriptions/FirstSubscriptionPage/container.js
- src/components/subscriptions/FirstSubscriptionPage/style.css
- src/components/users/settings/Settings.js
- src/components/users/settings/container.js
- src/components/utility/buttons/close/index.js
- src/components/utility/buttons/close/style.css
- src/components/utility/card/index.js
- src/components/utility/card/style.css
- src/components/utility/drop-down/index.js
- src/components/utility/links/index.js
- src/lib/engine/me/index.js
- src/routes/home/ModelDemo/example_treehouse.js
- src/routes/layouts/footer/index.js
- src/routes/layouts/login/index.js
- src/routes/layouts/login/style.css
- src/routes/router.js
- src/server/chargebee/constants.js
- src/server/chargebee/index.js
Several touches:
- Updated FAQ to contain information on private models
- Improved design for payment flow
- Fixed bug regarding clicking on the customer portal multiple times
- New upgrade button in account settings menu
- All users can officially see payment options
- Replaced several font awesome icons with Ionicons
> Paid model Completion

- src/components/spaces/show/header.js
- src/components/spaces/show/privacy-toggle/index.js
- src/components/spaces/show/privacy-toggle/style.css
- src/styles/variables.css
> Issue 202 upgrade link warning

- src/components/distributions/editor/TextForm/TextInput.js
We should do this a lot better, but this lowers the bound for now.
> Improving the isFunction check and lowering the data bound.

- src/components/subscriptions/FirstSubscription/container.js
- src/server/segment/constants.js
- src/server/segment/index.js
More to come, but this is a minimal, functional bit.
> Basic Commerce Tracking (renaming event name to specialty commerce event name).

- src/components/organizations/show/index.js
- src/modules/spaces/actions.js
and removing now obsolete TODO.
> Making space authors show up on the organizations page.

- package.json
- src/components/metrics/card/index.js
- src/components/metrics/card/name/style.css
- src/components/metrics/card/style.css
- src/components/spaces/denormalized-space-selector.js
- src/lib/engine/dgraph.js
- src/lib/engine/graph.js
> Distinguish intermediary metrics in UI

- package.json
- src/components/metrics/card/index.js
- src/components/metrics/card/name/style.css
- src/components/metrics/card/style.css
- src/components/spaces/denormalized-space-selector.js
- src/lib/engine/dgraph.js
- src/lib/engine/graph.js
Reverts getguesstimate/guesstimate-app#281
> Revert "Revert "Merge pull request #278 from getguesstimate/Show-intermediary…"

- src/lib/basic_graph/basic-graph-test.js
- src/lib/basic_graph/basic-graph.js
Appears to fix both client crashes and back propagation.
> No inf loops take 2

- src/components/organizations/show/index.js
- src/components/organizations/show/organizationMemberSelector.js
- src/components/organizations/show/style.css
- src/components/utility/card/index.js
- src/components/utility/card/style.css
- src/components/utility/drop-down/index.js
- src/lib/engine/organization.js
- src/lib/engine/user.js
- src/lib/engine/userOrganizationMemberships.js
- src/modules/organizations/actions.js
- src/modules/spaces/actions.js
- src/modules/users/actions.js
- src/routes/layouts/login/index.js
Show owners in 'select model'
Give organization an icon
Organization icon should show in 'Icons'.
Deletion should go to that user's page (personal or organizational)
> Organization Icons, closes Issue #292

- package.json
- src/lib/guesstimator/samplers/Function.js
- src/lib/guesstimator/samplers/distributions/distributions.js
I don't think these random generation methods are particularly efficient, but they were already existent.
Some examples:
Additionally, I've aliased the bernoulli distribution with a 'test' function for making multimodal conditional outputs easier:
Expanded:
We may be able to further alias this to make it even easier.
> Adds some basic discrete distributions via a package.

- package.json
- src/lib/guesstimator/samplers/Function.js
- src/lib/guesstimator/samplers/constructs/constructs.js
This makes an easy construct to add up many values conditioned on individual probabilities. 
Probabilities must sum to 1.
> Add scenarios function

- package.json
- src/lib/engine/graph.js
- src/lib/propagation/graph-propagation.js
- src/modules/guesstimate_form/actions.js
- src/modules/simulations/actions.js
- src/routes/middleware.js
- src/routes/sagas.js
We don't debounce the selected metric card, but we do debounce the other results.
> Debouncing functionality for metric card input

- src/components/metrics/card/MetricCardViewSection.js
- src/components/metrics/card/ViewSection.js
- src/components/metrics/card/index.js
MetricCardViewSection is the main section of the card; the part you see even when it is not expanded.
> Refactor metric card to split out 'MetricCardViewSection'

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/edge.js
- src/components/lib/FlowGrid/edges.js
> Slightly random arrow paths

- src/components/metrics/card/MetricCardViewSection/style.css
- src/components/metrics/card/name/style.css
- src/components/plans/index/style.css
- src/components/spaces/list_item/style.css
- src/routes/home/style.css
- src/routes/layouts/login/style.css
> Safari fix

- src/components/metrics/card/index.js
- src/components/metrics/card/updated.js
- src/components/spaces/canvas/index.js
Chain Test:
test: 1.14,0.98,0.91,0.96,0.97,1.17
master: 1.17, 0.95,0.96,0.99,1.09,1.04,0.99
Cold Load Test:
test: 17.53, 15.93, 17.93
master: 18.??, 16.57, 18.19
> Selective shared rendering methods for metric card cell updating.

- package.json
- src/components/metrics/modal/index.js
- src/lib/dataAnalysis.js
- src/modules/simulations/reducer.js
Also removes the unnecessary fastStats package. 
Test results:
Chain Test:
master: 2.28,2.01,2.07,1.85,1.89
test: 1.83,1.64,1.56,1.55,1.58
Cold Load Test:
master: 24.94,23.39 | 25, 23.74
test: 24.27,24.35 | 23.12, 24.42
> Perf improves stats function

- src/components/metrics/card/index.js
- src/components/metrics/card/updated.js
- src/components/spaces/canvas/index.js
Adds back in component updates, but fixes:
* Hover state bug
* Description Text Bug
* Modal Expansion Bug
should be reviewed, then deployed to stage and smoke tested, then pushed.
> Revert 333 revert 330 improve rendering

- .gitignore
Will this conflict with anything intended to go in git on your side?
> Ignoring tags files.

- src/components/distributions/editor/TextForm/DistributionSelector.js
- src/components/distributions/editor/TextForm/TextForm.js
- src/components/distributions/editor/TextForm/TextInput.js
- src/components/distributions/editor/style.css
- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/metrics/card/index.js
- src/components/metrics/card/style.css
- src/components/metrics/show/index.js
- src/components/spaces/canvas/index.js
- src/modules/selection/actions.js
- src/modules/selection/reducer.js
- Fixes a bug where selecting on a distribution shape would select the next cell (selection would happen on mouseUp, while the click happened on mouseDown).
- Metric is deselected after being opened. This stops a bug regarding input.
- The metric input no longer gets squished for mobile devices.  However, there still seems to be a bug for large empty cells.
- The Guesstimate form is a bit more small, to go along with recent changes to the cards.
- The value text box now expands as one types, similar to the name field.
> UI improvements

- src/components/distributions/editor/DataForm/DataViewer.js
- src/components/distributions/editor/DataForm/style.css
- src/components/distributions/editor/TextForm/TextInput.js
- src/components/lib/histogram.js
- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/MetricCardViewSection/style.css
- src/components/metrics/card/index.js
- src/components/simulations/histogram/index.js
- src/components/simulations/histogram/style.css
- src/lib/guesstimator/formatter/formatters/Null.js
- src/lib/guesstimator/samplers/None.js
Read commit names for details.
> Fixes multiple functionality & UI errors regarding data display

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/metrics/card/name/style.css
- src/components/spaces/show/style.css
> Minor embed color changes

- src/components/spaces/show/index.js
- src/routes/app.js
- src/routes/main.css
- src/server/elev/index.js
Closes https://github.com/getguesstimate/guesstimate-app/issues/367
> Selectively show elev

- src/components/spaces/list_item/index.js
- src/components/spaces/list_item/style.css
- src/components/users/show/index.js
> User space pictures

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/lib/FlowGrid/background-container.js
- src/components/lib/FlowGrid/cell.jsx
- src/components/lib/FlowGrid/edges.js
- src/components/lib/FlowGrid/filled-cell.js
- src/components/lib/FlowGrid/gridPoints.js
- src/components/spaces/canvas/index.js
> Multiple select background experiment

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/filled-cell.js
Reverts getguesstimate/guesstimate-app#372
> Revert "When card is dragged, do not show background"

- package.json
Fixes the binomial incorrect syntax crashing browser issue.
> Update discrete-sampling version.

- src/lib/guesstimator/formatter/formatters/DistributionTextProportion.js
> Added 1 in 10 syntax

- src/routes/router.js
Can't use string as navigation within site uses number.
> Correcting space show prop type in the router.

- package.json
- src/components/spaces/show/index.js
- src/routes/layouts/application/index.js
- src/routes/router.js
- webpack.config.js
This can go in now, but deploying it before prerendering and the netlify switchover will damage our results in other arenas (as this requires removing the html og tags). We can also wait for images then push this. But this section alone sets the title and description properly, with author information if present.
> Dynamic meta tags

- src/components/distributions/editor/TextForm/TextInput.js
- src/components/distributions/editor/style.css
This causes issues for undo in particular.
> Distribution editor forms should only be forms when being edited.

- src/components/distributions/editor/TextForm/TextForm.js
- src/components/distributions/editor/TextForm/TextInput.js
- src/components/distributions/editor/index.js
- src/components/metrics/card/index.js
This doesn't introduce the undo bug again, so is a safe reversion.
> Fixed function mode editor.

- src/components/spaces/cards/index.js
- src/components/spaces/cards/style.css
- src/components/spaces/index/index.js
- src/components/spaces/show/index.js
- src/lib/engine/space.js
Should not be deployed until the server (specifically the algolia section) is deployed (won't break if it is deployed first, just won't do much).
> Making organizations first and foremost owners of spaces.

- src/modules/checkpoints/actions.js
Only simulations that truly need to change should be affected.
> Undo-redo should not resimulate needlessly.

- src/components/organizations/show/index.js
- src/components/organizations/show/organizationMemberSelector.js
- src/components/organizations/show/style.css
- src/lib/engine/organization.js
- src/lib/guesstimate_api/resources/Organizations.js
- src/modules/organizations/actions.js
- src/modules/reducers.js
- src/modules/spaces/actions.js
- src/modules/userOrganizationInvitations/actions.js
- src/modules/userOrganizationMemberships/actions.js
Also added the views necessary to display invites and memberships differently:
> Added the store for invitations, and hooked up all the pipes.

- src/modules/spaces/actions.js
I don't know why this isn't causing a bug in production...
> Initialize checkpoints upon new model creation.

- src/modules/spaces/actions.js
Needs https://github.com/getguesstimate/guesstimate-server/pull/98
> Begin passing updated_at back up.

- src/components/organizations/show/index.js
- src/modules/organizations/actions.js
- src/modules/userOrganizationMemberships/actions.js
Fixes styling in non-admin mode
Sinks invitations, memberships, and members properly via the new representer
Cleans up the Invitee component a bit.
> Several misc. organization members portal fixes.

- src/components/distributions/editor/TextForm/TextInput.js
- src/components/lib/FlowGrid/FlowGrid.jsx
- Escape on metric value field selects metric.
- Mouse must move to make multiple selection.
> Minor editor enhancements #2

- src/components/metrics/card/index.js
- src/components/metrics/modal/index.js
Changes aren't as big as they look, mostly just unindented things.
> Metric modals should only render when they are open, not otherwise.

- src/modules/simulations/reducer.js
We'll short circuit and assign them manually, though, to avoid wasted work in this common edge case.
> Points should get statistics too, for rendering.

- src/components/spaces/show/index.js
- src/components/spaces/show/sidebar.js
> The space sidebar should only re-render when necessary.

- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/lib/FlowGrid/background-container.js
- src/components/lib/FlowGrid/edges.js
- src/lib/locationUtils.js
> Make the flowgrid background only render when necessary, along with its subcomponents.

- src/components/spaces/show/header.js
- src/components/spaces/show/index.js
> Make space header a class component with an appropriate shouldComponentUpdate method.

- src/components/distributions/editor/DataForm/DataForm.js
- src/components/distributions/editor/DataForm/DataViewer.js
- src/components/distributions/editor/TextForm/GuesstimateTypeIcon.js
- src/components/distributions/editor/TextForm/TextForm.js
- src/components/distributions/editor/TextForm/TextInput.js
- src/components/distributions/editor/index.js
This clarifies what operations cause data to be saved, and limit information transfer only to what is strictly necessary.
> Refactor the distribution text editor.

- src/components/spaces/show/Toolbar/index.js
- src/components/spaces/show/canvasViewForm.js
- src/components/spaces/show/privacy-toggle/index.js
- src/components/spaces/show/spaceName.js
- src/components/spaces/show/view-options/index.js
- src/components/utility/drop-down/index.js
- src/routes/layouts/login/index.js
This will be helpful for the import slurps work. This also seems a cleaner way to handle close on click, to me.
> Refactoring dropdowns so close on click works.

- src/modules/organizations/reducer.js
- src/modules/users/reducer.js
I also tried setting reduxCrud to use mutable resources, but it crashed everything, so let's leave that off for now.
> reduxCrud requires state to be immutable.

- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/lib/FlowGrid/background-container.js
- src/components/lib/FlowGrid/filled-cell.js
This also makes the dragged cell keep the height of the row at the time of the drag, both to help the background rendering issue and to prevent the height from jiterring.
> Fix up background layer, row heights calculation, and row height during drag to improve performance and UI on editor.

- src/components/organizations/show/index.js
- src/components/spaces/cards/index.js
- src/components/spaces/cards/style.css
- src/components/users/show/index.js
> New Model Button

- src/components/spaces/index/index.js
- src/components/spaces/index/style.css
- src/components/spaces/show/index.js
- src/components/utility/card/index.js
- src/components/utility/card/style.css
- src/components/utility/drop-down/index.js
- src/modules/search_spaces/actions.js
- src/modules/spaces/actions.js
- src/server/algolia/constants.js
- src/server/algolia/index.js
> Allow custom space index sort

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/lib/FlowGrid/cell.jsx
- src/components/metrics/card/index.js
> Style Formula Filling Nub

- src/routes/home/index.js
- src/routes/layouts/login/index.js
- The one instance I could find of '[X,Y]' syntax I found was updated.
- Added a new header item for organization creation.
> Minor style changes

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/spaces/show/index.js
- src/routes/layouts/application/index.js
This does a few things:
- Remove intercom when embedded
- Remove scrollbar when embedded
- Have scrollbar work appropriately for spaces show
> Minor style fixes for preview thumbnail

- src/routes/app.js
- src/server/elev/index.js
- src/server/segment/constants.js
- src/server/segment/index.js
Uses a set timeout b/c creating a jquery handle immediately doesn't detect the element if it hasn't finished loading.
> Tracks Elev usage via segment. Closes 286.

- src/modules/me/actions.js
- src/server/auth0/constants.js
A bit hacky, but the auth0 documentation was unyielding in providing a better solution.
> You should be logged out visibly when your token expires.

- src/components/distributions/summary/index.js
I'd like to actually adress this farther upstream, but I suspect that'd be a bigger change and this solves the immdiate problem.
> Cards should never show NaN.

- src/components/calculators/output.js
- src/modules/auto_fill_region/actions-test.js
- src/modules/auto_fill_region/actions.js
Also did a tiny cleanup in the calculator output function.
> Fixed and tested auto-fill bug.

- src/modules/users/actions.js
Goes with https://github.com/getguesstimate/guesstimate-server/pull/120
> Removing unused property.

- src/components/calculators/show.js
The button should be clickable as soon as all inputs are filled, then display a loading state until the results become available, then automatically show the result.
> Calculator calculate button improvements.

- src/components/metrics/card/index.js
- src/lib/guesstimator/formatter/formatters/Data.js
- src/lib/guesstimator/formatter/formatters/DistributionPointText.js
- src/lib/guesstimator/formatter/formatters/DistributionTextProportion.js
- src/lib/guesstimator/formatter/formatters/DistributionTextUpTo.js
- src/lib/guesstimator/formatter/formatters/DistributionTextUpToAlternate.js
- src/lib/guesstimator/formatter/formatters/Function.js
- src/lib/guesstimator/formatter/formatters/Null.js
- src/lib/guesstimator/formatter/formatters/lib.js
- src/lib/guesstimator/formatter/formatters/tests/DistributionNormalTextUpTo-test.js
- src/lib/guesstimator/formatter/formatters/tests/DistributionPointText-test.js
- src/lib/guesstimator/formatter/formatters/tests/DistributionTextUpToAlternate-test.js
- src/lib/guesstimator/formatter/index.js
- src/lib/guesstimator/samplers/DistributionBeta.js
- src/lib/guesstimator/samplers/DistributionLognormal.js
- src/lib/guesstimator/samplers/DistributionNormal.js
- src/lib/guesstimator/samplers/DistributionPoint.js
- src/lib/guesstimator/samplers/DistributionUniform.js
This switches all formatters to a regex-based mechanism, simplifying and DRYing the codebase.
> Improve formatters.

- src/components/calculators/calculator-space-selector.js
- src/components/calculators/show.js
- src/components/calculators/style.css
> Added privacy icon to the calculator when the calculator is private. Closes 596

- src/components/spaces/denormalized-space-selector.js
- src/components/spaces/show/Toolbar/index.js
- src/components/spaces/show/index.js
- src/lib/engine/calculator.js
- src/lib/engine/engine.js
- src/lib/engine/graph.js
- src/lib/engine/space.js
- src/modules/calculators/actions.js
- src/modules/guesstimates/reducer.js
- src/modules/metrics/reducer.js
- src/modules/spaces/actions.js
- src/modules/spaces/reducer.js
> Added list of calculators to space toolbar. Closes 593.

- src/components/distributions/editor/TextForm/TextForm.js
- src/components/distributions/editor/TextForm/TextInput.js
- src/components/distributions/editor/index.js
- src/components/distributions/editor/style.css
- src/components/metrics/card/index.js
- src/components/metrics/modal/index.js
- src/components/spaces/canvas/index.js
- src/lib/engine/space.js
- src/lib/factParser.js
- src/styles/variables.css
Also on stage-matthew.getguesstimate.com
> Adds decorators that wrap all valid and erroneous inputs with different styles. Closes 588 & 589

- src/components/spaces/show/Toolbar/index.js
- src/components/spaces/show/index.js
This relies on #593 as well, so should wait until that's been approved to go in.
> Adds a new calculator button to the toolbar list which triggers the new calculator form to load. Closes 594.

- src/components/spaces/show/Toolbar/index.js
…, and the whole list only show up if not empty.
> You shouldn't be able to create a calculator in the front end if you can't edit the space.

- src/components/calculators/new/CalculatorNew.js
- src/components/calculators/new/container.js
- src/components/calculators/new/new-calculator-selector.js
Also a smattering of random refactors I encountered along the way.
> Intermediates as outputs and enforcing that names are required.

- src/components/calculators/show/CalculatorExpandedShow.js
- src/components/calculators/show/CalculatorShow.js
- src/components/calculators/style.css
> Added basic help section to calculator

- src/components/calculators/show/CalculatorExpandedShow.js
- src/components/calculators/style.css
> Fixes to calculator help pane

- src/components/spaces/show/index.js
- src/lib/guesstimate_api/resources/Calculators.js
- src/modules/calculators/actions.js
Should go in after https://github.com/getguesstimate/guesstimate-server/pull/135.
> The delete button in the compressed view should work.

- src/components/distributions/editor/TextForm/TextForm.js
- src/components/distributions/editor/TextForm/TextInput.js
- src/components/distributions/editor/index.js
- src/components/distributions/editor/style.css
- src/components/metrics/card/index.js
- src/components/spaces/canvas/index.js
- src/lib/engine/facts.js
- src/lib/engine/guesstimate.js
- src/lib/guesstimator/samplers/simulator-worker/simulator/evaluator.js
- src/lib/propagation/graph-propagation.js
- src/modules/facts/actions.js
- src/modules/facts/reducer.js
- src/modules/organizations/actions.js
This has a number of things in it we may want to tune with time, but should be a good starting point. Works with facts on the server, after https://github.com/getguesstimate/guesstimate-server/pull/142.
> Adding support for organization specific facts.

- src/components/organizations/show/facts.js
> Adds field level errors to the new fact form.

- src/lib/engine/dgraph.js
- src/lib/engine/guesstimate.js
Also matches case of the fact failed reference error message.
> All instances of a fact handle should be translated.

- src/components/distributions/editor/TextForm/TextInput.js
I'm not 100% sure why this is necessary, but it works.
> Fixing input decorator issue with a timeout hack.

- src/components/facts/list/form.js
- src/components/facts/list/item.js
- src/components/facts/list/list.js
- src/components/facts/list/style.css
- src/components/organizations/show/index.js
- src/components/spaces/show/Toolbar/index.js
- src/components/spaces/show/header.js
- src/components/spaces/show/index.js
> Fact bank privacy ui

- src/components/lib/FlowGrid/utils.js
- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/index.js
- src/components/metrics/card/style.css
- src/components/metrics/card/token/index.js
> Metric sidebar

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/lib/FlowGrid/background-container.js
- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/index.js
- src/components/metrics/card/style.css
- src/components/metrics/card/updated.js
- src/components/spaces/canvas/index.js
- src/components/spaces/show/canvasViewForm.js
- src/lib/locationUtils.js
- src/modules/canvas_state/actions.js
- src/modules/canvas_state/prop_type.js
- src/modules/canvas_state/reducer.js
> New sensitivity mode

- src/components/plans/index/PlanIndex.js
- src/components/plans/index/StyleGuide.js
- src/components/plans/index/container.js
- src/components/plans/index/plans.js
Reverts getguesstimate/guesstimate-app#779
> Revert "Updated pricing information and some small refactors."

- src/lib/engine/__tests__/graph-test.js
- src/lib/engine/guesstimate.js
- src/lib/guesstimator/formatter/formatters/tests/DistributionNormalTextUpTo-test.js
It would be better to fix this properly, so to speak, by having the fact metrics have the right IDs, but this is quicker.
> Fixed bug in input detection.

- src/lib/generateVariableNames/generateMetricReadableId.js
- src/lib/generateVariableNames/nameToVariableName.js
- src/lib/generateVariableNames/tests/generateMetricReadableId-test.js
Fixes another bug with metric intelligent readable ID assignement.
> 09/07 Release:

- src/components/spaces/denormalized-space-selector.js
- src/components/spaces/show/index.js
- src/lib/engine/collections.js
- src/lib/engine/graph.js
- src/lib/engine/space.js
- src/lib/engine/utils.js
- src/lib/recorder.js
- src/modules/canvas_state/actions.js
- src/modules/canvas_state/reducer.js
- src/modules/spaces/actions.js
Also some refactors I encountered along the way.
> Don't try to set editsAllowed to any default values, just explicitly mark when it was set by the user.

- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/index.js
- src/components/metrics/card/style.css
- src/components/metrics/card/token/index.js
- src/components/metrics/card/token/style.css
> Writable facts ui for fact cards

- src/components/facts/list/form.js
- src/components/facts/list/list.js
- src/components/facts/list/style.css
- src/components/organizations/show/categories/category.js
- src/components/organizations/show/categories/form.js
- src/components/organizations/show/index.js
- src/components/organizations/show/style.css
> Fact categories styling

- src/components/facts/list/item.js
- src/components/facts/list/list.js
- src/components/facts/list/style.css
- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/organizations/show/facts/factGraph.js
- src/components/organizations/show/facts/style.css
- src/components/spaces/cards/index.js
- src/components/spaces/cards/style.css
> Fact graph UI refactor

- src/components/metrics/card/index.js
> Allow functions to be exported as faacts, regardless of node relationship type.

- src/components/spaces/show/index.js
- src/components/users/show/index.js
- src/lib/engine/space.js
- src/modules/organizations/actions.js
- src/modules/organizations/reducer.js
- src/modules/spaces/actions.js
And a few mild refactors.
This is definitely hacky, but it solves an open bug. We should revisit it later, if this goes in, and find a less hacky solution.
> Flag orgs as fully loaded when appropriate and use for space prepation checking.

- src/modules/spaces/actions.js
I actually don't know why this fixes the fact loading issue, but in light testing it seems to and doesn't seem like a bad change, so...
> Only load the space after all it's associated data is initialized.

- src/components/calculators/show/CalculatorShow.js
- src/components/calculators/style.css
- src/components/distributions/summary/index.js
- src/components/facts/list/item.js
- src/components/facts/list/list.js
- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/organizations/new/form.js
- src/components/organizations/show/facts/factGraph.js
- src/components/organizations/show/index.js
- src/components/spaces/show/Toolbar/index.js
- src/components/spaces/show/index.js
- src/components/spaces/show/style.css
- src/lib/DAG/DAG-test.js
- src/lib/DAG/DAG.js
- src/lib/guesstimator/formatter/formatters/Data.js
- src/lib/guesstimator/formatter/index.js
> Fix parser issue with guesstimates having empty arrays of data being inappropriately flagged as 'data' nodes.

- src/lib/dataAnalysis.js
- src/lib/engine/simulation.js
- src/lib/guesstimator/samplers/simulator-worker/simulator/evaluator.js
Bit worried about perf with this, but let me know what you think on it regardless. Let's not merge it though until we have more data.
> Fix no uncertainty display.

- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/index.js
- src/lib/dataAnalysis.js
- src/lib/engine/simulation.js
Various Performance Optimizations. Version is deployed to stage.getguesstimate.com
Performance Testing Results:
https://www.getguesstimate.com/models/7378?token=jyzDWf_MpKoA7tLGT1lwEOBDmQqWp2eowtaIHKEaw13VKdkoIKRFgj8WZZzz7k9_v0QB8asThPLw4Wu8b4-F7Q
> Further opt sample processing

- src/components/metrics/card/SensitivitySection/SensitivitySection.js
> Fix analysis mode when some samples have been filtered.

- src/components/metrics/card/SensitivitySection/SensitivitySection.js
- src/lib/dataAnalysis.js
Fix a bug with display of the adjusted confidence interval for large magnitude values.
> 10/31 Release:

- src/components/lib/FlowGrid/cell.jsx
- src/components/lib/FlowGrid/filled-cell.js
> Ensuring that post-drop handlers are only called if the drop is valid. Closes 908.

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/cell-empty.js
- src/components/lib/FlowGrid/cell.jsx
- src/components/lib/FlowGrid/filled-cell.js
- src/components/metrics/card/index.js
> Appropriate focusing behavior following a click on the boundary around a metric card. Closes #546

- src/components/distributions/editor/TextForm/DistributionSelector.js
- src/components/distributions/editor/TextForm/TextForm.js
> Preventing clicks on the lognormal icon when lognormal is an invalid choice. Closes #553.

- src/components/lib/histogram.js
- src/components/metrics/modal/index.js
- src/components/metrics/modal/style.css
- src/components/simulations/histogram/index.js
- src/components/simulations/histogram/style.css
- src/components/simulations/histogram_with_stats/index.js
- src/components/simulations/histogram_with_stats/style.css
> Interactive histogram range

- src/components/spaces/show/header.js
- src/components/spaces/show/index.js
- src/components/spaces/show/style.css
- src/lib/engine/space.js
This shows the org editor images on the spaces themselves, not that the cards.
@mmcdermott do you know if the data is always available in the cards?
> 941 show pictures of org editors

- package-lock.json
- package.json
> Deal with inconsequential security vulnerability

- .travis.yml
- package-lock.json
- package.json
- src/components/lib/FlowGrid/filled-cell.js
- src/components/utility/click-to-edit/index.js
- src/modules/modal/routes.js
This includes the relevant commits / code from https://github.com/getguesstimate/guesstimate-app/pull/989, but adapted to work in the current codebase.
> Add Travis CI to run linting and tests (Copy)

- src/components/organizations/show/index.tsx
Terraform will this branch with a different `NEXT_PUBLIC_API_BASE_URL`.
> No changes, testing k8s backend
