- src/components/spaces/show/index.js
- src/modules/spaces/actions.js
This is a quick fix for https://github.com/getguesstimate/guesstimate-app/issues/45
Basically, one big problem was that users going straight to specific models experienced a very slow response.  This loads that specific model in parallel (when needed), which is typically much faster.
> Load specific space on space open if needed

- src/components/distributions/editor/index.js
- src/modules/guesstimate_form/actions.js
- src/modules/search_spaces/actions.js
- src/server/guesstimate-api/constants.js
Instead of saving for each numeric keypress, save when that field is blurred.  
Also got ssl working for the heroku server (this was breaking for a bunch of people who used HTTPS everywhere).
> Reduce autosave use, use ssl for api

- src/components/users/show/index.js
- src/modules/search_spaces/actions.js
- src/modules/spaces/actions.js
- src/modules/users/actions.js
- src/routes/layouts/application/index.js
Previous all models and users were loaded into the browser for each request.  Most of this was redundant, because the important stuff was in the Algolia search results.  
Here I used the Algolia search results for the models and users.  This took a bit of fine tuning, but wasn't too bad. 
This addresses this issue: https://github.com/getguesstimate/guesstimate-app/issues/45
> Get model & user information from Algolia, not server

- src/components/spaces/canvas/index.js
- src/modules/guesstimates/actions.js
- src/modules/metrics/actions.js
- src/modules/spaces/actions.js
This is to eventually make sure that the server only updates with Algolia when non-graph items are changed.
> When model graph is changed, only update graph

- src/components/lib/grid/edges.js
- src/modules/guesstimates/reducer-test.js
- src/modules/guesstimates/reducer.js
- src/modules/metrics/reducer-test.js
- src/modules/metrics/reducer.js
This is one fix for the following bug.  It seems like there were a few problems here:
1) Some metrics were being created multiple times or were copied for some reason.
2) New guesstimates (inputs for metrics) were created on loop. 
I'm not sure exactly what caused these, but the reducers definitely shouldn't have allowed for this to create gigantic models of the same metrics and guesstimates.  I've solved the main issue here by enforcing uniqueness for metrics and guesstimates within models.  Later on we could look at the other two issues directly (this may take some time to reproduce).
Also, this is not a fix for the fact that some metrics are so huge that they won't actually get loaded.  Ideally there would be a back end fix for this; we would have a script to go through every single …
> Fix replication bug

- src/components/lib/grid/edge-container.js
- src/components/lib/grid/edges.js
- src/components/lib/grid/grid.css
- src/components/spaces/show/style.css
This addresses this issue: https://github.com/getguesstimate/guesstimate-app/issues/91
> Arrows should take 100% width

- src/components/distributions/editor/TextForm/DistributionSelector.js
- src/components/distributions/editor/style.css
- src/components/distributions/summary/index.js
- src/server/elev/index.js
- src/styles/variables.css
This did two things. 
- Add 'more' link when a metric card is expanded.
- Use the average percentile range instead of only using the high value.  This is important for all asymmetric distributions.
> More distributions button, closes #171

- src/components/organizations/show/index.js
- src/components/utility/drop-down/index.js
- src/lib/engine/engine.js
- src/lib/engine/organization.js
- src/routes/layouts/login/index.js
I think this component is rapidly building up some technical debt, but in the interest of speed here's this PR. Note how I am basically ignoring existing mechanisms of drop down closure, as they don't work unless the component renders twice (as on first render this.refs.[name] is undefined). I think we'll need to do a solution like this, or change the way dropdown works (which we should probably do, just the question of now v later).
> Adds Organizations dropdown menu for navigation to organization page. Closes 258.

- src/routes/layouts/login/index.js
Not all profile dropdown elements have an icon (b/c of ionicon) but all have headers, so this should solve our key issue.
> Giving all dropdown list elements in the profile dropdown unique keys.

- src/components/lib/histogram.js
- src/components/metrics/card/index.js
- src/components/metrics/modal/index.js
- src/components/simulations/histogram/index.js
This works for heavy tailed distributions, either symmetric or asymmetric. It's deployed to stage now. 
This will not work for anything with significant bimodality.
For uniform & normal distributions over ranges on the order of 10^150 or greater, card histograms don't render but the model remains accessible and usable (semi-graceful failure):
(though even in these cases the modal still renders the distribution.
For lognormals, things get that bad after ranges on the order of 10^10 or greater:
If those range sizes are unacceptable, we can try to add edge case logic for them somehow.
> Cuts off low density tails of the histogram. Closes 219.

- src/lib/basic_graph/basic-graph.js
- src/lib/basic_graph/basic-node.js
This stops the breakage from being as catastrophic, though adds no notice to the user that an infinite loop is the problem (and doesn't communicate that to anywhere else in the program).
> Changed recursive search algorithms to iterative and exit early upon self encounters to prevent infinite loops.

- src/routes/home/index.js
A one-letter typo: simple → simply.
> Fixed a typo

- src/components/lib/histogram.js
Some results.
Before (`[1,10]`):
After:
Before (`[1,1000]`):
After:
Before (`=normal(50,22)`):
After:
> Transform the ratio taking to ensure that small numbers don't disproportionately affect the results.

- src/lib/engine/graph.js
- src/lib/propagation/graph-propagation.js
The ``space.subset`` function was dramatically slowing things down, and wasn't needed when the graphFilter ``onlyHead`` was passed in.
> Do not clone graph before debounce

- src/components/distributions/summary/index.js
- src/components/distributions/summary/style.css
- src/components/metrics/card/style.css
- src/modules/simulations/reducer.js
Not that this doesn't show exactly the 5th to 95th percentiles.  Instead it shows the 10th percentiles for all numbers lower than the mean, and the 90th percentile for all numbers higher than the mean.  This means that it is still a 90% confidence interval, but that now it can not be outside the bounds of the mean.  We've found that when the range is outside the mean some people became very confused, plus the fact that in these cases, the extreme ends would be very significant.
> New Range Syntax for Metric Card

- src/components/lib/FlowGrid/filled-cell.js
- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/MetricCardViewSection/style.css
- src/components/metrics/card/index.js
- src/components/metrics/card/style.css
- src/components/simulations/stat_table/style.css
Previously the entire metric card was draggable.  This made editing with the text inputs difficult, especially with non-chrome browsers.
> Only the Stats metric card section should be draggable

- src/components/metrics/card/index.js
- src/components/spaces/canvas/index.js
Two small issues:
1) Nodes in the first row were not displaying analysis.
2) A 0 showed up in the analysis section when a metric was selected with less than 5 values.
> Fix minor issues regarding metric analysis.

- src/components/simulations/histogram/index.js
- src/lib/guesstimator/samplers/Data.js
- src/modules/simulations/reducer.js
The two datasets below are negated versions of each other, so their sum should be 0 in every sample.
> Don't resample data and show data histograms for even small data sets.

- package.json
- src/lib/guesstimator/samplers/Simulator.js
- src/lib/guesstimator/samplers/simulator-worker/simulator/evaluator.js
This PR makes us run the minimal number of in-order sample necessary to fully explore any intersections between dependent datasets, assuming relation via modularity. This probably doesn't make too much sense long term (relation via modularity) but in the context of that relation this preserves statistical properties and gives correct means while minimizing sample count. Some number theory functions are added to compute how many samples we need to run before we'll run out of intersections to explore.
*This is deployed to stage and should be manually tested before merging.*
> Proper data resampling.

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/filled-cell.js
There's still a small bug for some background color on bottom on occasion, but it's way better than dragging the entire card.
> When card is dragged, do not show background

- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/metrics/card/index.js
- src/components/spaces/canvas/index.js
- src/modules/copied/actions.js
- src/modules/guesstimates/reducer.js
- src/modules/metrics/actions.js
- src/modules/metrics/reducer.js
This is important from a UI perspective because with undo, we want one ctrl-z press to bring back an entire swath of deleted metrics, not them all one at a time.
> Multi-metric removal and addition should happen in one action.

- src/components/metrics/card/name/index.js
- src/components/metrics/card/name/style.css
- src/components/metrics/card/updated.js
In particular, this causes problems with undo (text areas steal focus). (deployed at stage.getguesstimate.com)
> Metric names shouldn't be forms when not being editing.

- src/components/metrics/card/name/style.css
This is currently deployed (along with the other hotfix pull request). This is a safety measure to ensure even when our strategies fail, the styling stays correct.
> Make textareas still be styled correctly as a fallback.

- src/components/lib/FlowGrid/FlowGrid.css
- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/lib/FlowGrid/background-container.js
- src/components/spaces/canvas/index.js
- src/modules/copied/actions.js
- src/modules/copied/reducer.js
The intended functionality is that the copied region of a canvas appears to have a dashed border around it.  After one paste, this goes away.  
One downside is that it's impossible to remove this selection without pasting, but I believe this is how similar tools do it.
> Added background color for copied region

- package.json
These at best work by happenstance and at worst unintentionally deploy the code to the wrong site. I don't know why they don't work, but until it is figured out it seems best to remove them entirely.
> Removing broken npm deploy rules.

- src/components/distributions/editor/TextForm/TextInput.js
- src/components/metrics/card/name/index.js
Draft JS Handler Documentation: 
"Cancelable Handlers (Optional) 
These prop functions are provided to allow custom event handling for a small set of useful events. By returning true from your handler, you indicate that the event is handled and the Draft core should do nothing more with it. By returning false, you defer to Draft to handle the event.
"
> Fix bug with returns in distribution editor.

- src/components/metrics/card/style.css
- src/components/spaces/canvas/style.css
- src/components/spaces/cards/style.css
The remove of the user-select css does mean that highlighting the canvas will now work (it would be better if this wouldn't, as it is not intended).  However, this seems like a minor issue.
> Css fixes to allow editing in Safari

- src/components/distributions/editor/TextForm/TextInput.js
- src/components/lib/FlowGrid/cell-empty.js
- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/index.js
- src/components/metrics/card/name/index.js
- For metric name, 'return' key selects value field.  Shift-return goes to a newline.
- For value field, 'return' key selects metric card.  Shift-return goes to a newline.
- Empty selected cards start off with name fields being selected.
Example currently on stage:
http://stage.getguesstimate.com/
> Auto select metric text forms

- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/spaces/canvas/index.js
- src/components/spaces/show/Toolbar/index.js
- src/components/spaces/show/Toolbar/style.css
- src/components/spaces/show/canvasViewForm.js
- src/components/spaces/show/header.js
- src/components/spaces/show/index.js
- src/components/spaces/show/spaceName.js
- src/components/spaces/show/style.css
- src/modules/copied/actions.js
- src/routes/layouts/application/style.css
- src/routes/layouts/header/style.css
- src/routes/layouts/login/style.css
> New Space Show Toolbar

- src/components/spaces/show/index.js
Otherwise changing spaces to an already loaded space doesn't reset the canvasState to the correct value. A cleaner solution (perhaps for a later refactor) would be to have an 'unset' value for the `editsAllowed` property, to which space dismount returned it.
> View options needs to reset both on mount and update

- src/components/spaces/show/index.js
When you make a new space, the 'editableByMe prop doesn't necessarily change, just the id does, (but we need the editableByMe prop check for when you load a space fresh, as there is no update where the id changes).
> Making a new model should reset you to edit mode if you start in view mode.

- src/components/distributions/editor/DataForm/DataForm.js
- src/components/distributions/editor/DataForm/DataViewer.js
- src/components/distributions/editor/TextForm/TextForm.js
- src/components/distributions/editor/index.js
Also changes from `*.map(` syntax to `_.map(*, ` syntax to avoid SI infinite recursion errors in dev.
> Saving data in the text form should run simulations.

- src/components/distributions/summary/index.js
- src/components/metrics/card/MetricCardViewSection/index.js
- src/components/metrics/card/token/index.js
- src/components/metrics/modal/index.js
- src/modules/simulations/reducer.js
Removed some unused code, some unnecessary defensive coding, and condensed the rest.
Additionally made more mild other refactors in a few other files.
> Refactor the distribution summary component

- src/lib/propagation/graph-propagation.js
- src/routes/app.js
With these changes, in the console, you can simply run Perf.printWasted() and it will print the timings from the last propagation run.
> Track performance in dev.

- src/lib/guesstimator/formatter/formatters/lib.js
- src/lib/guesstimator/formatter/formatters/tests/DistributionNormalTextUpTo-test.js
- src/lib/guesstimator/formatter/formatters/tests/DistributionPointText-test.js
Supports:
'K' (* 10^3)
'M' (* 10^6)
'B' (* 10^9)
'T' (* 10^12)
> Allow prefixes to be used in specifying points and ranges.

- src/components/spaces/show/Toolbar/index.js
This is not the most elegant solution, but for some reason I could not detect the canvas_state change on the requisite forbidEdits call ever actually affecting our component and this seemed clean enough for now.
> Further gating editsAllowed state on raw editableByMe property.

- src/components/lib/FlowGrid/FlowGrid.jsx
- src/components/lib/FlowGrid/background-container.js
If the state is calculated in Flowgrid, it is calculated on the previous incarnation of the rendered component. If it is calculated in the background container, that happens after the rows are rendered are thus gets the correct row heights.
> Fixes some jitteriness with background.

- src/lib/recorder.js
The recorder breaks when multiple components of the same name render in parallel; the fix would be for each component instance to have a unique ID; this would take more time than is warranted right now but this change will stop the broken recorder from running general in dev mode.
> Disable the recorder until a real fix is implemented.

- src/components/calculators/style.css
Makes images that would look like this:
Look like this:
> Images shouldn't extend beyond the width of the calculator section.

- src/components/calculators/show/CalculatorShow.js
- src/components/calculators/show/input.js
- src/components/calculators/show/output.js
- src/components/calculators/style.css
- Made input descriptions use Markdown.
- Added toggle for a stats description for the outputs.
> Calculator fixes

- src/components/distributions/editor/index.js
- src/components/metrics/card/index.js
- src/components/spaces/canvas/index.js
- src/components/spaces/denormalized-space-selector.js
- src/lib/engine/guesstimate.js
- src/lib/engine/space.js
- src/lib/propagation/graph-propagation.js
- src/modules/spaces/actions.js
Metrics are referenced by `id` within the `expression` field, not `readableId`. The translation to & from human readable `input` form takes place around the user interactions with the Guesstimate and prior to simulation. 
Must go in (and be deployed) after https://github.com/getguesstimate/guesstimate-server/pull/147
> Makes guesstimates be stored internally with an `expression` field, which generates a human readable input.

- src/components/organizations/show/facts/facts.js
Ostensibly this should chain to the actual API call via a promise or something, but this is sufficient for now. Alternatively, if the storage as state bothers you it can be made a class variable that's not part of state instead, that would also work.
> The new fact form should reset properly after fact creation.

- src/lib/engine/space.js
This is a bit hacky, and we should move this code to depend on expressions eventually.
Also, this also needs to be put into master before next deploy, but I'm hoping we can just merge this into the epic then the epic into master and sort it all in one swoop.
> Fixing metric relationship types by resolving to inputs prior to edge finding.

- src/lib/engine/facts.js
The shortest shared prefix approach was hurting the UX, and not working properly, so I just got rid of it for now. Won't much matter if we go to a dropdown soon anyways.
> Reverting the selector search algorithm to a direct search.

- README.md
HTTPs cloning works for everyone whether or not they have an ssh key set up.
> Use the https clone URL rather than the ssh URL.

- src/components/metrics/card/updated.js
This was causing all metric cards to update on any change.
> There are only 2 's's in 'guesstimate'

- src/lib/engine/facts.js
Non-org spaces should work now, and guesstimates with just titles should also work.
> Fixed two small bugs.

- src/components/spaces/show/index.js
- src/lib/engine/space.js
- src/lib/engine/utils.js
(not if either user or org is present).
Problem of facts showing as deleted metrics upon a cold load may, in fact, still be present, just at a vastly reduced frequency, but I'm not sure. Regardless, this certainly helps.
> Space only marks itself as prepared if the owner is present

- src/lib/propagation/DAG.js
- src/lib/propagation/node.js
By correcting a typo in `clearErrorFromDescendants` and ensuring nodes do not get removed from the unprocessed residual pool too early.
> Fixed error propagation issues 

- src/lib/engine/facts.js
- src/modules/facts/actions.js
- src/modules/organizations/actions.js
In particular, we may need to add a pseudo-empty ACI to the facts upon return as Rails Strong Params does not recognize  as a permitted scalar type within arrays.
> Added missing parameters into the facts upon fetch if they are returned with incomplete stats.

- src/components/facts/list/style.css
- src/components/spaces/show/header.js
- src/components/spaces/show/style.css
- Added 'break-word' to fact names and space sidebar areas, so they couldn't overflow.
- Added display: flex to facts, so they would be the same height as other elements in row.
- Removed 'expand' button.
> Minor UI improvements to fact graph functionality

- src/components/calculators/show/CalculatorShow.js
- src/components/calculators/style.css
- src/components/distributions/summary/index.js
- src/components/facts/list/item.js
- src/components/facts/list/list.js
- src/components/organizations/new/form.js
- src/components/organizations/show/facts/factGraph.js
- src/components/organizations/show/index.js
- src/components/spaces/show/Toolbar/index.js
- src/components/spaces/show/index.js
- src/components/spaces/show/style.css
- src/lib/DAG/DAG-test.js
- src/lib/DAG/DAG.js
Also rename parents -> inputs and children/dependants -> outputs across both DAG libs for consistency.
> Use the same DAG library (mostly) across the two DAG use cases.

- src/components/organizations/new/form.js
The radio buttons didn't have onChange handlers, so React didn't like that they had 'checked' props without 'readonly' set.
> Addressing console warning on new org page. Closes #705.

- src/components/spaces/show/spaceName.js
- src/components/spaces/show/style.css
- src/components/utility/drop-down/index.js
Refines the 'rename' menu for unnamed models, according to the spec laid out in #223.
It is staged on matthew.getguesstimate.com. Let me know if you'd like any style changes.
> Refining the rename menu for unnamed models. Closes #223.

- src/components/lib/histogram.js
Also, `barWidth` must also be finite before rendering.
> Always compute new scales, so that temporary error states, don't block histograms.
